---
# Database information
db_user: netbox_user
db_password: netbox_password
db_name: netbox

# Netbox Superuser information
nb_superuser: netbox_su
nb_email: 
nb_password: 

# Netbox version
netbox_vers: 3.7.0
