---
- name: Install Netbox
  hosts: netbox
  become: yes

  environment:
    DJANGO_SUPERUSER_PASSWORD: "{{ nb_password }}"

  vars_files:
  - config.yml
  
  tasks:
    - name: Checking OS version
      meta: end_play
      when: ansible_distribution != 'Ubuntu' or ansible_distribution_version != '22.04'

    - name: Install preliminary packages
      import_tasks: base/initial.yml

    - name: Install and configure PostgreSQL
      import_tasks: base/postgres.yml

    - name: Install Redis
      import_tasks: base/redis.yml
    
    - name: Download and install Netbox
      import_tasks: base/netbox.yml

    - name: Run Netbox Upgrade script
      import_tasks: base/upgrade.yml

    - name: Create Netbox superuser
      import_tasks: base/superuser.yml

    - name: Create Housekeeping task and timer
      import_tasks: base/housekeeping.yml

    - name: Install Gunicorn
      import_tasks: base/gunicorn.yml

    - name: Install nginx
      import_tasks: base/http.yml
