---
- hosts: all
  become: yes

  vars_files:
    - vars.yml

  pre_tasks:
    - name: "Install packages"
      apt: "name={{ item }} state=present"
      with_items:
        - postgresql

    - name: "Install Python packages"
      pip: "name={{ item }} state=present"
      with_items:
        - psycopg2-binary

  tasks:
    - name: "Find out if PostgreSQL is initialized"
      ansible.builtin.stat:
        path: "/var/lib/postgresql/data/pg_hba.conf"
      register: postgres_data

    - name: "Initialize PostgreSQL"
      become: yes
      become_user: postgres
      command: "/usr/lib/postgresql/14/bin/initdb -D /var/lib/postgresql/data"
      when: not postgres_data.stat.exists

    - name: "Start and enable services"
      service: "name={{ item }} state=started enabled=yes"
      with_items:
        - postgresql

    - name: "Create database"
      postgresql_db:
        state: present
        name: "{{ db_name }}"
      become_user: postgres

    - name: "Create user"
      postgresql_user:
        state: present
        name: "{{ db_user }}"
        password: "{{ db_password }}"
      become_user: postgres

    - name: "Grant user access"
      postgresql_privs:
        type: database
        database: "{{ db_name }}"
        roles: "{{ db_user }}"
        grant_option: no
        privs: all
      become_user: postgres

  handlers:
    - name: restart postgres
      service: "name=postgresql state=restarted"

